---
jupyter:
  jupytext:
    formats: r_notebooks///ipynb,r_markdown///Rmd
    text_representation:
      extension: .Rmd
      format_name: rmarkdown
      format_version: '1.2'
      jupytext_version: 1.11.1
  kernelspec:
    display_name: R 4.1.0
    language: R
    name: ir41
---

# Bluebetters and systolic blood pressure

## Notes

### Question of interest

### Data

### Results

### Discussion

## Full Results

### Setup the notebook

```{r}
library(DBI)        # importing data
library(tidyverse)  # for ggplt
library(Rmisc)      # for CI
library(BSDA)       # for z-test
```

### Import the data

```{r}
# get data
con <- dbConnect(RSQLite::SQLite(), "..\\data\\source.db3")
fibres <- dbReadTable(con, "glass_fibres")
dbDisconnect(con)
```

```{r}
head(fibres)
```

### Visualise the data

```{r}
# frequency histogram
ggplot(fibres, aes(Strength)) +
  geom_histogram(bins = 10)
```

```{r}
# probability plot
qqnorm(fibres$Strength); qqline(fibres$Strength)
```

### Analyse the data

```{r tags=c("parameters")}
# declare parameters for z-test
mu0 <- 1.5
strength <- fibres$Strength
sd <- sd(strength)
```

```{r}
# get mean, zconfint_mean
CI(strength)
```

```{r}
# run the z-test
z.test(strength, alternative = "greater", mu = mu0, sigma.x = sd)
```